name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          stable: false
          go-version: ${{ matrix.go-version }}

      - name: Set up dependencies
        run: |
          go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Unit Tests
        run: go test -race -v $(go list ./... | grep -v /test/) -coverprofile=coverage.out

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          flag-name: Go-${{ matrix.go }}
          parallel: true

  integration_test:
    strategy:
      matrix:
        distro: [ 'ubuntu:20.04', 'ubuntu:22.04', 'debian:bullseye' ]
        database: [mysql, sqlite]
        web-server: [nginx, apache]
        go-version: [ 1.19.x ]
    runs-on: ubuntu-latest
    container:
      image:  ${{ matrix.distro }}
      options: --user root
      volumes:
        - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
    steps:
      - name: Container preparation
        run: |
          apt -y update
          apt-get install ca-certificates -y
          update-ca-certificates

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          stable: false
          go-version: ${{ matrix.go-version }}

      - name: Set up dependencies
        run: go mod download

      - name: Tests
        run: |
          cd cmd/gameapctl/
          go build .
          ./gameapctl --non-interactive panel install --path=/var/www/gameap --host=127.0.0.1 --web-server=${{ matrix.web-server}} --database=${{ matrix.database}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: /var/log/
          retention-days: 5

  test-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Unit Tests
        run: go test -race -v $(go list ./... | grep -v /test/)
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
